name: Deploy Storybook to GH Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    container:
      image: node:10
    steps:
      - name: Install dependencies
        run: npm i
      - name: Deploy to GH Pages
        run: npm run deploy-storybook
